### ISSUE TITLE
how to know if otp change after enter ?

### ISSUE THREAD

**Issue by mitulmarsonia** [sarojraut/SROTPView#2]
Once enter otp then after remove last 1 digit form otp screen then didn't realise which one remove. Can you help me out ?

**Comment by sarojraut** [comment]
You can get otp changed value on
 `otpView.otpEnteredString = { pin in
            print("The entered pin is \(pin)")
        }`

**Comment by mitulmarsonia** [comment]
Yes right if enter any digit then get in otpEnteredString but if remove 2 digit then check hasEnteredAllOTP is return true. I want add validation if otp not enter then ask to user.

**Comment by sarojraut** [comment]
Thanks for addressing the issue.Issue has been resolved
